#!/bin/sh

# Media player
apt install -y mpv
# Screen recording
apt install -y obs-studio
apt install -y xdg-desktop-portal-wlr
# Video Editor
apt install -y kdenlive
# Vector Graphics Editor
apt install -y inkscape
# Stellarium Virtual Planetarium
apt install -y stellarium
# Xournal++
apt install -y xournalpp
# PCB Design Software
apt install -y kicad
# Blender 3D Modeling
apt install -y blender
# Mutt Email
apt install -y mutt
# Audacity Audio Editor
apt install -y audacity
# Typing game
apt install -y typespeed
# 7zip
apt install -y 7zip
# Gedit Text Editor
apt install -y gedit
# PHP
apt install -y php
# GNU Image Manipulation Program
apt install -y gimp
