#!/bin/sh

# Sway Wayland compositor
apt install -y sway
# Chromium browser
apt install -y chromium
# Wayland clipboard utilities
apt install -y wl-clipboard
# Git version control
apt install -y git
# Sway default backgrounds
apt install -y sway-backgrounds
# ALSA utils
apt install -y alsa-utils
# Xwayland compatibility layer for apps expecting X
apt install -y xwayland
# The GNU info command
apt install -y info
# Bash documentation (accessed with info)
apt install -y bash-doc
