#!/bin/sh

# GCC
apt install -y gcc
# system call tracer
apt install -y strace
# library call tracer
apt install -y ltrace
# development man pages
apt install -y manpages-dev
# make command
apt install -y make
# GCC targeting i386
apt install -y gcc-i686-linux-gnu
# Vim text editor
apt install -y vim
# QEMU PC Emulator
apt install -y qemu-system-x86
# GDB
apt install -y gdb
