#!/bin/sh

QEMU_PKG=qemu-system-x86_64
if [[ $(arch) = i686 ]]
then
	QEMU_PKG=qemu-system-i386
fi

# ALSA
apk add alsa-utils alsa-utils-doc
# Man
apk add man-db man-db-doc
# Sudo
apk add sudo
# Sway Man Pages
apk add sway-doc
# Vim
apk add vim
# Git
apk add git
# Foot Man Pages (The default Sway terminal)
apk add foot-doc
# Sway Background (Fix blank background)
apk add swaybg
# OpenSSH Client (Adds commands like ssh-keygen for example)
apk add openssh-client
# QEMU with GTK UI (PC Emulator)
apk add $QEMU_PKG qemu-doc qemu-ui-gtk
# QEMU img utility
apk add qemu-img
# QEMU ALSA audio driver
apk add qemu-audio-alsa
# GNU Bash
apk add bash bash-doc
# GNU Coreutils
apk add coreutils coreutils-doc
# GNU Texinfo (adds the info command to read GNU documentation)
apk add texinfo
# Strace
apk add strace strace-doc
# Ltrace
apk add ltrace ltrace-doc
