#!/bin/sh

# GNU Make
apk add make
# GNU Compiler Collection
apk add gcc gcc-doc
# Musl Header Files (libc)
apk add musl-dev
# Linux Man Pages
apk add man-pages
# GNU Debugger
apk add gdb
# Universal Ctags
apk add ctags
# NASM Assembler
apk add nasm nasm-doc
# i386 GCC to enable cross compiling
apk add gcc-i386-elf
